#!/usr/bin/env bash
# This script installs and configures nginx

sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
