#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

echo "$1"
sudo mysqldump -u root -p"$1" --all-databases | sudo tee backup.sql > /dev/null
current_date=$(date +"%d-%m-%Y")
tar -cvzf "$current_date.tar.gz" backup.sql
