#!/usr/bin/bash
# Script to install and configure nginx to listen on port 80 and stop any
# service using the port
sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install nginx
sudo service apache2 stop
sudo service nginx restart
