#!/usr/bin/env bash
# Script to install and configure nginx to listen on port 80 and stop
# apache from using port 80
sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install nginx && sudo service nginx restart
