#!/usr/bin/env bash
# Script to install and configure nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
