#!/usr/bin/env bash
# This script displays a message indefinitely and displays another message when
#+ it receives a SIGTERM signal.

trap "echo 'I am invincible'" TERM

while true;
do
	echo "To infinity and beyond"
	sleep 2
done
