#!/usr/bin/env bash
# This script reads /etc/passwd and displays the name, id, and home directory
#+ path of each user.

while read -r LINE;
do
	USERNAME=$(echo "$LINE" | cut -f1 -d ":")
	ID=$(echo "$LINE" | cut -f3 -d ":")
	HOME_D=$(echo "$LINE" | cut -f6 -d ":")
	echo "$USERNAME:$ID:$HOME_D"
done</etc/passwd
