#!/usr/bin/env bash
# This script reads /etc/passwd and displays the name, id, and home directory
#+ path of each user.

IFS=":"

while read -r NAME PASSWORD USRID GID UIDINFO HOME_D SHELL;
do
	echo "The user $NAME is part of the $GID gang, lives in $HOME_D and rides $SHELL. $USRID's place is protected by the password $PASSWORD, more info about the user here: $UIDINFO"
done</etc/passwd
