#!/usr/bin/env bash
# This script displays "Best School" 10 times but on the 9th iteration also
#+ displays "Hi" in a new line.

i=10

while [ "$i" -gt 0 ]
do
	echo "Best School"

	if [ "$i" -eq 2 ]
	then
		echo "Hi"
	fi

	(( i-- ))
done
