#!/usr/bin/env bash
# This script iterates 10 times displaying a message with a special message for
#+ the 4th iteration and 8th iteration.

i=0

while (( "$i" < 10 ))
do
	if (("$i" == 3 ))
	then
		echo "bad luck"

	elif (( "$i" == 7 ))
	then
		echo "good luck"

	else
		echo "Best School"
	fi

	(( i++ ))
done
