#!/usr/bin/env bash
# This script uses case clauses to display different messages for some of the
special values in Chinese, Japanese, and Italian cultures.

i=1

while [ "$i" -le 20 ]
do
	echo "$i"

	case "$i" in
	     	4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( i += 1 ))
done
