#!/usr/bin/env bash
# This script displays the hour and minute values a 12-hour clock could have.

# Ignore the obvious bug of 0 and 12 being the same but displayed separately,
#+ The task was set up as such.

HOUR=0

while [ "$HOUR" -le 12 ]
do
	    echo "Hour: $HOUR"
      	    MINUTE=1

	    while [ "$MINUTE" -lt 60 ]
      	    do
	            echo "$MINUTE"
	    	    (( MINUTE += 1 ))
	    done

	    (( HOUR += 1 ))
done
